# Generated by Django 2.2.5 on 2022-05-20 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Albums', verbose_name='画册的ID'),
        ),
        migrations.CreateModel(
            name='commentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_id', models.IntegerField(default=0, verbose_name='回复的ID')),
                ('reply_type', models.CharField(default='comment', max_length=10, verbose_name='回复的类型')),
                ('from_uid', models.IntegerField(default=0, verbose_name='回复用户的ID')),
                ('to_uid', models.IntegerField(default=0, verbose_name='回复目标的ID')),
                ('content', models.CharField(max_length=100, verbose_name='回复的内容')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.comment', verbose_name='评论的ID')),
            ],
            options={
                'verbose_name': '回复',
                'verbose_name_plural': '回复',
                'db_table': 'vgpic_commentReply',
            },
        ),
    ]
