# Generated by Django 2.2.5 on 2022-05-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_auto_20220509_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='comments',
            field=models.IntegerField(default=0, verbose_name='评论数量'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='stars',
            field=models.IntegerField(default=0, verbose_name='收藏数量'),
        ),
        migrations.AlterField(
            model_name='useralbum',
            name='albums_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Albums', verbose_name='画册ID'),
        ),
    ]
