# Generated by Django 2.2.5 on 2022-05-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_auto_20220511_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='cover_img',
            field=models.ImageField(default='https://img.afqaq.com/images/2022/04/18/sky1.jpg', upload_to='', verbose_name='Pic defaltimg'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='created_time',
            field=models.DateField(auto_now_add=True, verbose_name='画册创建时间'),
        ),
        migrations.AlterField(
            model_name='useralbum',
            name='albums_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Albums', verbose_name='画册ID'),
        ),
    ]
