# Generated by Django 2.2.5 on 2022-05-13 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0009_auto_20220513_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='creator',
        ),
        migrations.AddField(
            model_name='albums',
            name='creator',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者的ID'),
        ),
        migrations.AlterField(
            model_name='useralbum',
            name='albums_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Albums', verbose_name='画册ID'),
        ),
    ]
