# Generated by Django 2.2.5 on 2022-05-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_auto_20220513_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='cover_img',
            field=models.ImageField(default='group1/M00/00/18/wKixgWKC-MCAOin6AAFipXLsyCU5017204', upload_to='', verbose_name='Pic defaltimg'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='img_list',
            field=models.TextField(max_length=500, verbose_name='画册中图片的ID'),
        ),
        migrations.AlterField(
            model_name='useralbum',
            name='albums_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Albums', verbose_name='画册ID'),
        ),
    ]
