# Generated by Django 2.2.5 on 2022-05-20 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0013_auto_20220520_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralbum',
            name='albums_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Albums', verbose_name='画册ID'),
        ),
    ]
